language: node_js

branches:
  only:
    - master

node_js:
  - "lts/*"
  - "node"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - "yarn lint"
  - "yarn test:coverage"
  - "yarn build"

notifications:
  email:
    - ram@hiddentao.com
